# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setBaseSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("background-color: white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: grey;")
        self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(200)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QFrame(self.centralwidget)
        self.verticalLayout_2.setMaximumSize(QtCore.QSize(300, 300))
        self.verticalLayout_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalLayout_2.setStyleSheet("")
        self.verticalLayout_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalLayout_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayout_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.first_btn_1 = QtWidgets.QPushButton(self.verticalLayout_2)
        self.first_btn_1.setMinimumSize(QtCore.QSize(0, 125))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.first_btn_1.setFont(font)
        self.first_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.first_btn_1.setStyleSheet("QPushButton {\n"
"background-color: #3AB0FF; color: white; border: none;\n"
"border-top-left-radius: 20px; border-top-right-radius: 20px;\n"
"line-height: 0.5 !important;\n"
"}\n"
"\n"
"")
        self.first_btn_1.setObjectName("first_btn_1")
        self.verticalLayout_5.addWidget(self.first_btn_1)
        self.first_btn_2 = QtWidgets.QPushButton(self.verticalLayout_2)
        self.first_btn_2.setMinimumSize(QtCore.QSize(0, 175))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.first_btn_2.setFont(font)
        self.first_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.first_btn_2.setStyleSheet("QPushButton {\n"
"    background-color: #3AB0FF; color: white; border: none;\n"
"    border-bottom-left-radius: 20px; border-bottom-right-radius: 20px;\n"
"}\n"
"")
        self.first_btn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui_files\\../../../../Users/aerki/Downloads/Untitled(3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.first_btn_2.setIcon(icon)
        self.first_btn_2.setIconSize(QtCore.QSize(200, 200))
        self.first_btn_2.setObjectName("first_btn_2")
        self.verticalLayout_5.addWidget(self.first_btn_2)
        self.horizontalLayout_3.addWidget(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(300, 300))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sec_btn_1 = QtWidgets.QPushButton(self.frame)
        self.sec_btn_1.setMinimumSize(QtCore.QSize(0, 125))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.sec_btn_1.setFont(font)
        self.sec_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sec_btn_1.setStyleSheet("QPushButton {\n"
"background-color: #3AB0FF; color: white; border: none;\n"
"border-top-left-radius: 20px; border-top-right-radius: 20px;\n"
"line-height: 0.5 !important;\n"
"}")
        self.sec_btn_1.setObjectName("sec_btn_1")
        self.verticalLayout_3.addWidget(self.sec_btn_1)
        self.sec_btn_2 = QtWidgets.QPushButton(self.frame)
        self.sec_btn_2.setMinimumSize(QtCore.QSize(0, 175))
        self.sec_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sec_btn_2.setStyleSheet("QPushButton {\n"
"background-color: #3AB0FF; color: white; border: none;\n"
"border-bottom-left-radius: 20px; border-bottom-right-radius: 20px;\n"
"}\n"
"")
        self.sec_btn_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ui_files\\../../../../Users/aerki/Downloads/Untitled(4).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sec_btn_2.setIcon(icon1)
        self.sec_btn_2.setIconSize(QtCore.QSize(200, 200))
        self.sec_btn_2.setObjectName("sec_btn_2")
        self.verticalLayout_3.addWidget(self.sec_btn_2)
        self.horizontalLayout_4.addWidget(self.frame)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "НАЗВАНИЕ"))
        self.label_4.setText(_translate("MainWindow", "Программа для визуализации движения тел на графиках"))
        self.first_btn_1.setText(_translate("MainWindow", "Одномерная\n"
"система\n"
"координат"))
        self.sec_btn_1.setText(_translate("MainWindow", "Двумерная\n"
"система\n"
"координат"))
