# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\sec-input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 450)
        Dialog.setStyleSheet("background-color: white;\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"  background-color:#F9F2ED;\n"
"  color: black;\n"
"  padding: 7px 25px;\n"
"margin-top: 5px;\n"
"border-radius: 10px;\n"
"margin-right: 10px;\n"
"margin-left: 200px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background-color: #3AB0FF;\n"
"color: white;\n"
" }\n"
"QTabWidget::pane { \n"
"   border: none;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_rpd = QtWidgets.QWidget()
        self.tab_rpd.setObjectName("tab_rpd")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_rpd)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.tab_rpd)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(15)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMaximumSize(QtCore.QSize(380, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_11.addWidget(self.label_18)
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_speed = QtWidgets.QCheckBox(self.frame_2)
        self.cb_speed.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_speed.setText("")
        self.cb_speed.setIconSize(QtCore.QSize(16, 16))
        self.cb_speed.setObjectName("cb_speed")
        self.horizontalLayout.addWidget(self.cb_speed)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.label_speed = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_speed.setFont(font)
        self.label_speed.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 15px;\n"
"margin-right: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_speed.setReadOnly(True)
        self.label_speed.setObjectName("label_speed")
        self.horizontalLayout.addWidget(self.label_speed)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_11.addWidget(self.frame_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_start = QtWidgets.QCheckBox(self.frame_6)
        self.cb_start.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_start.setText("")
        self.cb_start.setIconSize(QtCore.QSize(16, 16))
        self.cb_start.setObjectName("cb_start")
        self.horizontalLayout_3.addWidget(self.cb_start)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_start = QtWidgets.QLineEdit(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_start.setFont(font)
        self.label_start.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 15px;\n"
"margin-right: 15px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_start.setReadOnly(True)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_3.addWidget(self.label_start)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_11.addWidget(self.frame_6)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cb_end = QtWidgets.QCheckBox(self.frame_4)
        self.cb_end.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_end.setText("")
        self.cb_end.setIconSize(QtCore.QSize(16, 16))
        self.cb_end.setObjectName("cb_end")
        self.horizontalLayout_5.addWidget(self.cb_end)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.label_end = QtWidgets.QLineEdit(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_end.setFont(font)
        self.label_end.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 25px;\n"
"margin-right: 15px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_end.setReadOnly(True)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_5.addWidget(self.label_end)
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_11.addWidget(self.frame_4)
        self.horizontalLayout_10.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setMaximumSize(QtCore.QSize(380, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setTextFormat(QtCore.Qt.PlainText)
        self.label_19.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_12.addWidget(self.label_19)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cb_speed_y = QtWidgets.QCheckBox(self.frame_8)
        self.cb_speed_y.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_speed_y.setText("")
        self.cb_speed_y.setIconSize(QtCore.QSize(16, 16))
        self.cb_speed_y.setObjectName("cb_speed_y")
        self.horizontalLayout_6.addWidget(self.cb_speed_y)
        self.label_30 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_6.addWidget(self.label_30)
        self.label_speed_y = QtWidgets.QLineEdit(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_speed_y.setFont(font)
        self.label_speed_y.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 15px;\n"
"margin-right: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_speed_y.setReadOnly(True)
        self.label_speed_y.setObjectName("label_speed_y")
        self.horizontalLayout_6.addWidget(self.label_speed_y)
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_12.addWidget(self.frame_8)
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cb_start_y = QtWidgets.QCheckBox(self.frame_11)
        self.cb_start_y.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_start_y.setText("")
        self.cb_start_y.setIconSize(QtCore.QSize(16, 16))
        self.cb_start_y.setObjectName("cb_start_y")
        self.horizontalLayout_9.addWidget(self.cb_start_y)
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.label_start_y = QtWidgets.QLineEdit(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_start_y.setFont(font)
        self.label_start_y.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 15px;\n"
"margin-right: 15px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_start_y.setReadOnly(True)
        self.label_start_y.setObjectName("label_start_y")
        self.horizontalLayout_9.addWidget(self.label_start_y)
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        self.label_17.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.verticalLayout_12.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cb_end_y = QtWidgets.QCheckBox(self.frame_10)
        self.cb_end_y.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_end_y.setText("")
        self.cb_end_y.setIconSize(QtCore.QSize(16, 16))
        self.cb_end_y.setObjectName("cb_end_y")
        self.horizontalLayout_8.addWidget(self.cb_end_y)
        self.label_14 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.label_end_y = QtWidgets.QLineEdit(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_end_y.setFont(font)
        self.label_end_y.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 25px;\n"
"margin-right: 15px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_end_y.setReadOnly(True)
        self.label_end_y.setObjectName("label_end_y")
        self.horizontalLayout_8.addWidget(self.label_end_y)
        self.label_15 = QtWidgets.QLabel(self.frame_10)
        self.label_15.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_12.addWidget(self.frame_10)
        self.horizontalLayout_10.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_28 = QtWidgets.QFrame(self.tab_rpd)
        self.frame_28.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_27.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_time = QtWidgets.QCheckBox(self.frame_28)
        self.cb_time.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_time.setText("")
        self.cb_time.setIconSize(QtCore.QSize(16, 16))
        self.cb_time.setObjectName("cb_time")
        self.horizontalLayout_2.addWidget(self.cb_time)
        self.label_4 = QtWidgets.QLabel(self.frame_28)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_time = QtWidgets.QLineEdit(self.frame_28)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 45px;\n"
"margin-right: 15px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_time.setReadOnly(True)
        self.label_time.setObjectName("label_time")
        self.horizontalLayout_2.addWidget(self.label_time)
        self.label_5 = QtWidgets.QLabel(self.frame_28)
        self.label_5.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_27.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.frame_28)
        self.frame_12 = QtWidgets.QFrame(self.tab_rpd)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_4.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_4.setSpacing(125)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ok_btn = QtWidgets.QPushButton(self.frame_12)
        self.ok_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ok_btn.setFont(font)
        self.ok_btn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: #3AB0FF;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #009EFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0014FF;\n"
"}")
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout_4.addWidget(self.ok_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.frame_12)
        self.cancel_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: #F87474;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f54040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #f01313;\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_4.addWidget(self.cancel_btn)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.tabWidget.addTab(self.tab_rpd, "")
        self.tab_rypd = QtWidgets.QWidget()
        self.tab_rypd.setObjectName("tab_rypd")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_rypd)
        self.verticalLayout_13.setContentsMargins(5, 0, 5, 10)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_14 = QtWidgets.QFrame(self.tab_rypd)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(20)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.frame_18 = QtWidgets.QFrame(self.frame_14)
        self.frame_18.setMaximumSize(QtCore.QSize(390, 16777215))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_45 = QtWidgets.QLabel(self.frame_18)
        self.label_45.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_25.addWidget(self.label_45)
        self.frame_17 = QtWidgets.QFrame(self.frame_18)
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.cb_speed_start = QtWidgets.QCheckBox(self.frame_17)
        self.cb_speed_start.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_speed_start.setText("")
        self.cb_speed_start.setIconSize(QtCore.QSize(16, 16))
        self.cb_speed_start.setObjectName("cb_speed_start")
        self.horizontalLayout_17.addWidget(self.cb_speed_start)
        self.label_31 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_17.addWidget(self.label_31)
        self.label_speed_start = QtWidgets.QLineEdit(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_speed_start.setFont(font)
        self.label_speed_start.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 15px;\n"
"margin-right: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_speed_start.setReadOnly(True)
        self.label_speed_start.setObjectName("label_speed_start")
        self.horizontalLayout_17.addWidget(self.label_speed_start)
        self.label_32 = QtWidgets.QLabel(self.frame_17)
        self.label_32.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_17.addWidget(self.label_32)
        self.verticalLayout_17.addLayout(self.horizontalLayout_17)
        self.verticalLayout_25.addWidget(self.frame_17)
        self.frame_16 = QtWidgets.QFrame(self.frame_18)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.cb_speed_end = QtWidgets.QCheckBox(self.frame_16)
        self.cb_speed_end.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_speed_end.setText("")
        self.cb_speed_end.setIconSize(QtCore.QSize(16, 16))
        self.cb_speed_end.setObjectName("cb_speed_end")
        self.horizontalLayout_14.addWidget(self.cb_speed_end)
        self.label_26 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_14.addWidget(self.label_26)
        self.label_speed_end = QtWidgets.QLineEdit(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_speed_end.setFont(font)
        self.label_speed_end.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 15px;\n"
"margin-right: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_speed_end.setReadOnly(True)
        self.label_speed_end.setObjectName("label_speed_end")
        self.horizontalLayout_14.addWidget(self.label_speed_end)
        self.label_27 = QtWidgets.QLabel(self.frame_16)
        self.label_27.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_14.addWidget(self.label_27)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        self.verticalLayout_25.addWidget(self.frame_16)
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.cb_boost = QtWidgets.QCheckBox(self.frame_20)
        self.cb_boost.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_boost.setText("")
        self.cb_boost.setIconSize(QtCore.QSize(16, 16))
        self.cb_boost.setObjectName("cb_boost")
        self.horizontalLayout_15.addWidget(self.cb_boost)
        self.label_28 = QtWidgets.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_15.addWidget(self.label_28)
        self.label_boost = QtWidgets.QLineEdit(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_boost.setFont(font)
        self.label_boost.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 7px;\n"
"margin-right: 8px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_boost.setReadOnly(True)
        self.label_boost.setObjectName("label_boost")
        self.horizontalLayout_15.addWidget(self.label_boost)
        self.label_29 = QtWidgets.QLabel(self.frame_20)
        self.label_29.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_15.addWidget(self.label_29)
        self.verticalLayout_18.addLayout(self.horizontalLayout_15)
        self.verticalLayout_25.addWidget(self.frame_20)
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.cb_start_2 = QtWidgets.QCheckBox(self.frame_19)
        self.cb_start_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_start_2.setText("")
        self.cb_start_2.setIconSize(QtCore.QSize(16, 16))
        self.cb_start_2.setObjectName("cb_start_2")
        self.horizontalLayout_13.addWidget(self.cb_start_2)
        self.label_24 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_13.addWidget(self.label_24)
        self.label_start_2 = QtWidgets.QLineEdit(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_start_2.setFont(font)
        self.label_start_2.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 18px;\n"
"margin-right: 25px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_start_2.setReadOnly(True)
        self.label_start_2.setObjectName("label_start_2")
        self.horizontalLayout_13.addWidget(self.label_start_2)
        self.label_25 = QtWidgets.QLabel(self.frame_19)
        self.label_25.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        self.verticalLayout_16.addLayout(self.horizontalLayout_13)
        self.verticalLayout_25.addWidget(self.frame_19)
        self.frame_15 = QtWidgets.QFrame(self.frame_18)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.cb_end_2 = QtWidgets.QCheckBox(self.frame_15)
        self.cb_end_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_end_2.setText("")
        self.cb_end_2.setIconSize(QtCore.QSize(16, 16))
        self.cb_end_2.setObjectName("cb_end_2")
        self.horizontalLayout_11.addWidget(self.cb_end_2)
        self.label_20 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.label_end_2 = QtWidgets.QLineEdit(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_end_2.setFont(font)
        self.label_end_2.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 30px;\n"
"margin-right: 25px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_end_2.setReadOnly(True)
        self.label_end_2.setObjectName("label_end_2")
        self.horizontalLayout_11.addWidget(self.label_end_2)
        self.label_23 = QtWidgets.QLabel(self.frame_15)
        self.label_23.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.verticalLayout_25.addWidget(self.frame_15)
        self.horizontalLayout_24.addWidget(self.frame_18)
        self.frame_21 = QtWidgets.QFrame(self.frame_14)
        self.frame_21.setMaximumSize(QtCore.QSize(390, 16777215))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_46 = QtWidgets.QLabel(self.frame_21)
        self.label_46.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_24.addWidget(self.label_46)
        self.frame_23 = QtWidgets.QFrame(self.frame_21)
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.cb_speed_start_y = QtWidgets.QCheckBox(self.frame_23)
        self.cb_speed_start_y.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_speed_start_y.setText("")
        self.cb_speed_start_y.setIconSize(QtCore.QSize(16, 16))
        self.cb_speed_start_y.setObjectName("cb_speed_start_y")
        self.horizontalLayout_19.addWidget(self.cb_speed_start_y)
        self.label_37 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_19.addWidget(self.label_37)
        self.label_speed_start_y = QtWidgets.QLineEdit(self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_speed_start_y.setFont(font)
        self.label_speed_start_y.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 20px;\n"
"margin-right: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_speed_start_y.setReadOnly(True)
        self.label_speed_start_y.setObjectName("label_speed_start_y")
        self.horizontalLayout_19.addWidget(self.label_speed_start_y)
        self.label_38 = QtWidgets.QLabel(self.frame_23)
        self.label_38.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_19.addWidget(self.label_38)
        self.verticalLayout_20.addLayout(self.horizontalLayout_19)
        self.verticalLayout_24.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.frame_21)
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.cb_speed_end_y = QtWidgets.QCheckBox(self.frame_24)
        self.cb_speed_end_y.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_speed_end_y.setText("")
        self.cb_speed_end_y.setIconSize(QtCore.QSize(16, 16))
        self.cb_speed_end_y.setObjectName("cb_speed_end_y")
        self.horizontalLayout_20.addWidget(self.cb_speed_end_y)
        self.label_39 = QtWidgets.QLabel(self.frame_24)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_20.addWidget(self.label_39)
        self.label_speed_end_y = QtWidgets.QLineEdit(self.frame_24)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_speed_end_y.setFont(font)
        self.label_speed_end_y.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 20px;\n"
"margin-right: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_speed_end_y.setReadOnly(True)
        self.label_speed_end_y.setObjectName("label_speed_end_y")
        self.horizontalLayout_20.addWidget(self.label_speed_end_y)
        self.label_40 = QtWidgets.QLabel(self.frame_24)
        self.label_40.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_20.addWidget(self.label_40)
        self.verticalLayout_21.addLayout(self.horizontalLayout_20)
        self.verticalLayout_24.addWidget(self.frame_24)
        self.frame_26 = QtWidgets.QFrame(self.frame_21)
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.cb_boost_y = QtWidgets.QCheckBox(self.frame_26)
        self.cb_boost_y.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_boost_y.setText("")
        self.cb_boost_y.setIconSize(QtCore.QSize(16, 16))
        self.cb_boost_y.setObjectName("cb_boost_y")
        self.horizontalLayout_22.addWidget(self.cb_boost_y)
        self.label_43 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_22.addWidget(self.label_43)
        self.label_boost_y = QtWidgets.QLineEdit(self.frame_26)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_boost_y.setFont(font)
        self.label_boost_y.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 10px;\n"
"margin-right: 3px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_boost_y.setReadOnly(True)
        self.label_boost_y.setObjectName("label_boost_y")
        self.horizontalLayout_22.addWidget(self.label_boost_y)
        self.label_44 = QtWidgets.QLabel(self.frame_26)
        self.label_44.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_22.addWidget(self.label_44)
        self.verticalLayout_23.addLayout(self.horizontalLayout_22)
        self.verticalLayout_24.addWidget(self.frame_26)
        self.frame_25 = QtWidgets.QFrame(self.frame_21)
        self.frame_25.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.cb_start_2_y = QtWidgets.QCheckBox(self.frame_25)
        self.cb_start_2_y.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_start_2_y.setText("")
        self.cb_start_2_y.setIconSize(QtCore.QSize(16, 16))
        self.cb_start_2_y.setObjectName("cb_start_2_y")
        self.horizontalLayout_21.addWidget(self.cb_start_2_y)
        self.label_41 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_21.addWidget(self.label_41)
        self.label_start_2_y = QtWidgets.QLineEdit(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_start_2_y.setFont(font)
        self.label_start_2_y.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 20px;\n"
"margin-right: 22px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_start_2_y.setReadOnly(True)
        self.label_start_2_y.setObjectName("label_start_2_y")
        self.horizontalLayout_21.addWidget(self.label_start_2_y)
        self.label_42 = QtWidgets.QLabel(self.frame_25)
        self.label_42.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_21.addWidget(self.label_42)
        self.verticalLayout_22.addLayout(self.horizontalLayout_21)
        self.verticalLayout_24.addWidget(self.frame_25)
        self.frame_22 = QtWidgets.QFrame(self.frame_21)
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.cb_end_2_y = QtWidgets.QCheckBox(self.frame_22)
        self.cb_end_2_y.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_end_2_y.setText("")
        self.cb_end_2_y.setIconSize(QtCore.QSize(16, 16))
        self.cb_end_2_y.setObjectName("cb_end_2_y")
        self.horizontalLayout_16.addWidget(self.cb_end_2_y)
        self.label_33 = QtWidgets.QLabel(self.frame_22)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_16.addWidget(self.label_33)
        self.label_end_2_y = QtWidgets.QLineEdit(self.frame_22)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_end_2_y.setFont(font)
        self.label_end_2_y.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 30px;\n"
"margin-right: 22px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_end_2_y.setReadOnly(True)
        self.label_end_2_y.setObjectName("label_end_2_y")
        self.horizontalLayout_16.addWidget(self.label_end_2_y)
        self.label_34 = QtWidgets.QLabel(self.frame_22)
        self.label_34.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_16.addWidget(self.label_34)
        self.verticalLayout_19.addLayout(self.horizontalLayout_16)
        self.verticalLayout_24.addWidget(self.frame_22)
        self.horizontalLayout_24.addWidget(self.frame_21)
        self.verticalLayout_13.addWidget(self.frame_14)
        self.frame_27 = QtWidgets.QFrame(self.tab_rypd)
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cb_time_2 = QtWidgets.QCheckBox(self.frame_27)
        self.cb_time_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.cb_time_2.setText("")
        self.cb_time_2.setIconSize(QtCore.QSize(16, 16))
        self.cb_time_2.setObjectName("cb_time_2")
        self.horizontalLayout_12.addWidget(self.cb_time_2)
        self.label_21 = QtWidgets.QLabel(self.frame_27)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_12.addWidget(self.label_21)
        self.label_time_2 = QtWidgets.QLineEdit(self.frame_27)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_2.setFont(font)
        self.label_time_2.setStyleSheet("QLineEdit {\n"
"  border-radius: 10px;\n"
"  border: 2px solid #F9F2ED;\n"
"  padding: 2px 10px;\n"
"margin-left: 50px;\n"
"margin-right: 23px;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #3AB0FF;\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #F9F2ED;\n"
"}")
        self.label_time_2.setReadOnly(True)
        self.label_time_2.setObjectName("label_time_2")
        self.horizontalLayout_12.addWidget(self.label_time_2)
        self.label_22 = QtWidgets.QLabel(self.frame_27)
        self.label_22.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_12.addWidget(self.label_22)
        self.verticalLayout_26.addLayout(self.horizontalLayout_12)
        self.verticalLayout_13.addWidget(self.frame_27)
        self.frame_13 = QtWidgets.QFrame(self.tab_rypd)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(125)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.ok_btn_2 = QtWidgets.QPushButton(self.frame_13)
        self.ok_btn_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ok_btn_2.setFont(font)
        self.ok_btn_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: #3AB0FF;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #009EFF;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0014FF;\n"
"}")
        self.ok_btn_2.setObjectName("ok_btn_2")
        self.horizontalLayout_23.addWidget(self.ok_btn_2)
        self.cancel_btn_2 = QtWidgets.QPushButton(self.frame_13)
        self.cancel_btn_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_btn_2.setFont(font)
        self.cancel_btn_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: #F87474;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f54040;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #f01313;\n"
"}")
        self.cancel_btn_2.setObjectName("cancel_btn_2")
        self.horizontalLayout_23.addWidget(self.cancel_btn_2)
        self.verticalLayout_13.addWidget(self.frame_13)
        self.tabWidget.addTab(self.tab_rypd, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_18.setText(_translate("Dialog", "x"))
        self.label_12.setText(_translate("Dialog", "Скорость:"))
        self.label_3.setText(_translate("Dialog", "м/с"))
        self.label_6.setText(_translate("Dialog", "Начальная\n"
"позиция:"))
        self.label_start.setPlaceholderText(_translate("Dialog", "0"))
        self.label_7.setText(_translate("Dialog", "м"))
        self.label_8.setText(_translate("Dialog", "Конечная\n"
"позиция:"))
        self.label_9.setText(_translate("Dialog", "м"))
        self.label_19.setText(_translate("Dialog", "y"))
        self.label_30.setText(_translate("Dialog", "Скорость:"))
        self.label_11.setText(_translate("Dialog", "м/с"))
        self.label_16.setText(_translate("Dialog", "Начальная\n"
"позиция:"))
        self.label_start_y.setPlaceholderText(_translate("Dialog", "0"))
        self.label_17.setText(_translate("Dialog", "м"))
        self.label_14.setText(_translate("Dialog", "Конечная\n"
"позиция:"))
        self.label_15.setText(_translate("Dialog", "м"))
        self.label_4.setText(_translate("Dialog", "Время:"))
        self.label_5.setText(_translate("Dialog", "с"))
        self.ok_btn.setText(_translate("Dialog", "продолжить"))
        self.cancel_btn.setText(_translate("Dialog", "отмена"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rpd), _translate("Dialog", "РПД"))
        self.label_45.setText(_translate("Dialog", "x"))
        self.label_31.setText(_translate("Dialog", "Начальная\n"
"скорость:"))
        self.label_32.setText(_translate("Dialog", "м/с"))
        self.label_26.setText(_translate("Dialog", "Конечная\n"
"скорость:"))
        self.label_27.setText(_translate("Dialog", "м/с"))
        self.label_28.setText(_translate("Dialog", "Ускорение:"))
        self.label_29.setText(_translate("Dialog", "м/с²"))
        self.label_24.setText(_translate("Dialog", "Начальная\n"
"позиция:"))
        self.label_start_2.setPlaceholderText(_translate("Dialog", "0"))
        self.label_25.setText(_translate("Dialog", "м"))
        self.label_20.setText(_translate("Dialog", "Конечная \n"
"позиция:"))
        self.label_23.setText(_translate("Dialog", "м"))
        self.label_46.setText(_translate("Dialog", "y"))
        self.label_37.setText(_translate("Dialog", "Начальная\n"
"скорость:"))
        self.label_38.setText(_translate("Dialog", "м/с"))
        self.label_39.setText(_translate("Dialog", "Конечная\n"
"скорость:"))
        self.label_40.setText(_translate("Dialog", "м/с"))
        self.label_43.setText(_translate("Dialog", "Ускорение:"))
        self.label_44.setText(_translate("Dialog", "м/с²"))
        self.label_41.setText(_translate("Dialog", "Начальная\n"
"позиция:"))
        self.label_start_2_y.setPlaceholderText(_translate("Dialog", "0"))
        self.label_42.setText(_translate("Dialog", "м"))
        self.label_33.setText(_translate("Dialog", "Конечная\n"
"позиция:"))
        self.label_34.setText(_translate("Dialog", "м"))
        self.label_21.setText(_translate("Dialog", "Время:"))
        self.label_22.setText(_translate("Dialog", "с"))
        self.ok_btn_2.setText(_translate("Dialog", "продолжить"))
        self.cancel_btn_2.setText(_translate("Dialog", "отмена"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rypd), _translate("Dialog", "РУПД"))
